### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by kheaactua** [Kupoman/blendergltf#87]
I receive an export error when attempting to export in gLTF v1.0 using Blender 2.76 and the gLTF exporter I downloaded today (which I think is off `master`)

```
$ Traceback (most recent call last):
  File "/home/matt/.config/blender/2.76/scripts/addons/blendergltf-master/__init__.py", line 345, in execute
    gltf = export_gltf(data, settings)
  File "/home/matt/.config/blender/2.76/scripts/addons/blendergltf-master/blendergltf.py", line 1516, in export_gltf
    state['output'].update(export_buffers(state))
  File "/home/matt/.config/blender/2.76/scripts/addons/blendergltf-master/blendergltf.py", line 1019, in export_buffers
    gltf['accessors'] = list(itertools.chain(*[buf.export_accessors(state) for buf in buffers]))
  File "/home/matt/.config/blender/2.76/scripts/addons/blendergltf-master/blendergltf.py", line 1019, in <listcomp>
    gltf['accessors'] = list(itertools.chain(*[buf.export_accessors(state) for buf in buffers]))
  File "/home/matt/.config/blender/2.76/scripts/addons/blendergltf-master/blendergltf.py", line 373, in export_accessors
    gltf['byteStride'] = value.buffer_view['bytestride']
TypeError: string indices must be integers

location: <unknown location>:-1

location: <unknown location>:-1
```

This seems to be independent of what export options I'm using.  I tried printing out `value`, but I wasn't able to get useful debugging information.

**Comment by Kupoman** [comment]
Should be fixed now, thanks for reporting the bug.

**Comment by kheaactua** [comment]
worked!  Thanks =)

**Comment by guzuomuse** [comment]
@Kupoman ,this bug still exists. not gone.
blender version:2.78c
any idea?

**Comment by guzuomuse** [comment]
![image](https://user-images.githubusercontent.com/5040829/30481464-5f135374-9a51-11e7-99a6-b23308c22ce4.png)

**Comment by Kupoman** [comment]
@guzuomuse, this looks like a different problem than the one originally reported. Could you please open a new report and provide a .blend file or steps to reproduce the problem?

**Comment by guzuomuse** [comment]
@Kupoman ,for sure. i will open a new issue and attache the **.blend** file to it.
https://github.com/Kupoman/blendergltf/issues/102
